BOOKS = [
  [ "Genesis", 15 ],
  [ "Exodus", 15 ],
  [ "Leviticus", 15 ],
  [ "Number", 15 ],
  [ "Deuteronomy", 14 ],
  [ "Joshua", 14 ],
  [ "Judges", 14 ],
  [ "Ruth", 10 ],
  [ "1 Samuel", 14 ],
  [ "2 Samuel", 14 ],
  [ "1 Kings", 14 ],
  [ "2 Kings", 14 ],
  [ "1 Chronicles", 15 ],
  [ "2 Chronicles", 15 ],
  [ "Ezra", 12 ],
  [ "Nehemiah", 13 ],
  [ "Esther", 12 ],
  [ "Job", 15 ],
  [ "Psalms", 16 ],
  [ "Proverbs", 14 ],
  [ "Ecclesiastes", 12 ],
  [ "Song of Solomon", 10 ],
  [ "Isaiah", 15 ],
  [ "Jeremiah",  15 ],
  [ "Lamentations", 12 ],
  [ "Ezekiel", 15 ],
  [ "Daniel", 13 ],
  [ "Hosea", 12 ],
  [ "Joel", 8 ],
  [ "Amos", 12 ],
  [ "Obadiah", 5 ],
  [ "Jonah", 8 ],
  [ "Micah", 10 ],
  [ "Nahum", 47 ],
  [ "Habakkuk", 56 ],
  [ "Zephaniah", 8 ],
  [ "Haggai", 5 ],
  [ "Zechariah", 12 ],
  [ "Malachi", 8 ],
  [ "Matthew", 15 ],
  [ "Mark", 14 ],
  [ "Luke", 15 ],
  [ "John", 14 ],
  [ "Acts", 15 ],
  [ "Romans", 13 ],
  [ "1 Corinthians", 13 ],
  [ "2 Corinthians", 12 ],
  [ "Galatians", 12 ],
  [ "Ephesians", 12 ],
  [ "Philippians", 10 ],
  [ "Colossians", 10 ],
  [ "1 Thessalonians", 10 ],
  [ "2 Thessalonians", 8 ],
  [ "1 Timothy", 10 ],
  [ "2 Timothy", 10 ],
  [ "Titus", 8 ],
  [ "Philemon", 5 ],
  [ "Hebrews", 13 ],
  [ "1 John", 10 ],
  [ "2 John", 6 ],
  [ "3 John", 5 ],
  [ "Jude", 5 ],
  [ "Revelation", 13 ]
].freeze
